### ISSUE TITLE
Update SQL documentation to include TRIM()

### ISSUE THREAD

**Issue by ehsky** [MateuszDabrowski/mateuszdabrowski.pl#2]
Thanks for the great Marketing Cloud content Mateusz! 

I don't think i'm the first person to say that my go to place is your documentation. Therefor i though to notify that the trim documentation could be simplified by using TRIM() instead of nesting them: LTRIM(RTRIM('   data from webform '))

https://mateuszdabrowski.pl/docs/sql/sfmc-sql-string-functions/#ltrim-and-rtrim

```sql title="Noone likes useless whitespace in their database"
SELECT
      LTRIM('   data from webform ')        AS CleanLeftSide    /* Output: 'data from webform ' */
    , RTRIM('   data from webform ')        AS CleanRightSide   /* Output: '   data from webform' */
    , TRIM('   data from webform ') AS CleanBothSides   /* Output: 'data from webform' */
```

**Comment by MateuszDabrowski** [comment]
Thank you for your kind words @ehsky !

I used LTRIM(RTRIM()) approach as SFMC used SQL Server 2016 and TRIM() was added in SQL Server 2017, but just checked it again and indeed TRIM() now works. Same for TRANSLATE()! 

So it seems you just found out there was a silent, undocumented SQL Server update for SFMC :)
Will definitely have to update the docs, thank you!

**Comment by MateuszDabrowski** [comment]
I just pushed the update covering both TRIM and version bump: https://github.com/MateuszDabrowski/mateuszdabrowski.pl/commit/20316a833eca11a5e0dc5f067fde4e7787022908 It will be visible on the website with the nearest production deployment :)
